# Development environment configuration
environment: development

# Use mock data in development
data_sources:
  type: mock
  mock:
    enabled: true
    data_file: "tests/fixtures/mock_data.json"

# Display settings for development
display:
  type: terminal  # or 'web', 'simulator'
  terminal:
    clear_screen: true
    width: 80
    height: 40
  web:
    port: 8080
    auto_open: true
  simulator:
    scale: 10
    show_grid: true

# Logging
logging:
  level: DEBUG
  file: "logs/development.log"

# Development tools
development:
  hot_reload: true
  debug_mode: true
  profiling: false